import { Card } from '../../../shared/ui/Card';
import { Badge } from '../../../shared/ui/Badge';
import { GitCommit, CheckCircle2, GitPullRequest, Plus, Minus } from 'lucide-react';
import { cn } from '../../../shared/lib/utils';

export function VersionDAG({ versions, activeVersionId, onSelect }: { versions: any[], activeVersionId: string, onSelect: (id: string) => void }) {
  return (
    <Card className="p-4 overflow-hidden h-[600px] overflow-y-auto font-mono text-sm">
      <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-4 font-sans border-b border-slate-200 dark:border-slate-800 pb-2">Version Graph</h3>
      <div className="space-y-0 text-slate-600 dark:text-slate-400">
        {versions.map((v) => {
          const isActive = v.id === activeVersionId;
          return (
            <div key={v.id} className="relative group cursor-pointer" onClick={() => onSelect(v.id)}>
              {/* Branching visual logic (simplified for v1 as per requirements) */}
              <div className={cn(
                "flex items-start gap-2 p-2 rounded-md transition-colors",
                isActive ? "bg-blue-50 dark:bg-blue-900/20" : "hover:bg-slate-50 dark:hover:bg-slate-900/50"
              )}>
                <div className="flex flex-col items-center justify-center shrink-0 w-8 pt-0.5">
                  {v.isBranch ? <span>├──</span> : <span>│</span>}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className={cn(
                      "font-bold",
                      isActive ? "text-blue-700 dark:text-blue-400" : "text-slate-900 dark:text-slate-100",
                      v.isCurrent && "text-green-700 dark:text-green-400"
                    )}>{v.id}</span>
                    {v.isCurrent && (
                      <span className="flex items-center text-[10px] bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300 px-1.5 py-0.5 rounded font-sans uppercase font-bold tracking-wider">
                        <CheckCircle2 className="h-3 w-3 mr-1"/> Current
                      </span>
                    )}
                  </div>
                  <div className="mt-1 flex flex-wrap gap-1 font-sans">
                    <Badge variant="outline" className="text-[10px] uppercase">{v.generatedBy}</Badge>
                    {v.eventsCount > 0 && <span className="text-xs text-slate-500">{v.eventsCount} Events</span>}
                  </div>
                  <p className="text-xs text-slate-500 mt-1 font-sans">{v.date}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </Card>
  );
}

export function VersionProvenance({ version }: { version: any }) {
  if (!version) return null;

  return (
    <Card className="p-5 space-y-6">
      <h3 className="font-semibold text-slate-900 dark:text-slate-100 border-b border-slate-200 dark:border-slate-800 pb-2">Lineage & Metadata</h3>
      
      <div className="space-y-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Generated By</p>
          <div className="flex items-center gap-2">
            <GitPullRequest className="h-4 w-4 text-blue-500" />
            <span className="text-sm font-medium">{version.generatedBy}</span>
          </div>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Parent Version</p>
          <div className="flex items-center gap-2">
            <GitCommit className="h-4 w-4 text-slate-500" />
            <span className="text-sm font-medium font-mono">{version.parent || 'None'}</span>
          </div>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-2">Career Events Consumed</p>
          <div className="flex flex-wrap gap-2">
            {version.events.map((e: string) => (
              <Badge key={e} variant="secondary" className="font-mono">{e}</Badge>
            ))}
            {version.events.length === 0 && <span className="text-sm text-slate-500">No events</span>}
          </div>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Approved Changes</p>
          <span className="text-sm">{version.changesCount} recommendations applied</span>
        </div>

        <div className="grid grid-cols-2 gap-4 pt-2">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Created</p>
            <span className="text-sm">{version.date}</span>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1">Promoted</p>
            <span className="text-sm font-medium">{version.isCurrent ? 'Yes' : 'No'}</span>
          </div>
        </div>
      </div>
    </Card>
  );
}

export function GroupedDiffViewer({ diffs }: { diffs: any[] }) {
  if (!diffs || diffs.length === 0) {
    return (
      <Card className="p-8 text-center text-slate-500">
        <p>No textual changes in this version compared to its parent.</p>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {diffs.map((diffGroup, idx) => (
        <Card key={idx} className="overflow-hidden">
          <div className="bg-slate-50 dark:bg-slate-900/50 px-4 py-2 border-b border-slate-200 dark:border-slate-800">
            <h4 className="font-semibold text-sm uppercase tracking-wider">{diffGroup.section}</h4>
          </div>
          <div className="p-0 font-mono text-sm divide-y divide-slate-200 dark:divide-slate-800">
            {diffGroup.changes.map((change: any, cIdx: number) => (
              <div key={cIdx} className={cn(
                "p-3 flex items-start gap-3",
                change.type === 'add' ? "bg-green-50 dark:bg-green-950/20 text-green-800 dark:text-green-300" :
                change.type === 'remove' ? "bg-red-50 dark:bg-red-950/20 text-red-800 dark:text-red-300" :
                "text-slate-600 dark:text-slate-400"
              )}>
                {change.type === 'add' && <Plus className="h-4 w-4 mt-0.5 shrink-0" />}
                {change.type === 'remove' && <Minus className="h-4 w-4 mt-0.5 shrink-0" />}
                {change.type === 'none' && <div className="h-4 w-4 shrink-0" />}
                <p className="whitespace-pre-wrap">{change.text}</p>
              </div>
            ))}
          </div>
        </Card>
      ))}
    </div>
  );
}
