from enum import Enum

class CareerEventType(str, Enum):
    PROJECT_ADDED = "PROJECT_ADDED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_REMOVED = "PROJECT_REMOVED"
    
    EXPERIENCE_ADDED = "EXPERIENCE_ADDED"
    EXPERIENCE_UPDATED = "EXPERIENCE_UPDATED"
    EXPERIENCE_REMOVED = "EXPERIENCE_REMOVED"
    
    SKILL_ADDED = "SKILL_ADDED"
    SKILL_UPDATED = "SKILL_UPDATED"
    SKILL_REMOVED = "SKILL_REMOVED"
    
    EDUCATION_ADDED = "EDUCATION_ADDED"
    EDUCATION_UPDATED = "EDUCATION_UPDATED"
    
    CERTIFICATION_ADDED = "CERTIFICATION_ADDED"
    CERTIFICATION_UPDATED = "CERTIFICATION_UPDATED"
    
    SUMMARY_UPDATED = "SUMMARY_UPDATED"
